CREATE TABLE SM_USER_TB
(USER_NO NUMBER(4) CONSTRAINT SM_USER_TB_PK PRIMARY KEY,
USER_ID VARCHAR2(50) UNIQUE NOT NULL,
USER_PW VARCHAR2(50) NOT NULL,
USER_EMAIL VARCHAR2(50) NOT NULL,
USER_BIRTH VARCHAR2(16) NOT NULL,
USER_STATE NUMBER(1) DEFAULT 1,
USER_GENDER NUMBER(1) DEFAULT 1,
USER_MOD_DATE DATE DEFAULT SYSDATE,
USER_CRE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SM_USER_TB IS '사용자';
COMMENT ON COLUMN SM_USER_TB.USER_NO IS '고유번호';
COMMENT ON COLUMN SM_USER_TB.USER_ID IS '아이디';
COMMENT ON COLUMN SM_USER_TB.USER_PW IS '비밀번호';
COMMENT ON COLUMN SM_USER_TB.USER_EMAIL IS '이메일';
COMMENT ON COLUMN SM_USER_TB.USER_BIRTH IS '생년월일';
COMMENT ON COLUMN SM_USER_TB.USER_STATE IS '상태(1:정상, 2:금지)';
COMMENT ON COLUMN SM_USER_TB.USER_GENDER IS '성별(1:남자, 2:여자)';
COMMENT ON COLUMN SM_USER_TB.USER_MOD_DATE IS '수정일자';
COMMENT ON COLUMN SM_USER_TB.USER_CRE_DATE IS '생성일자';

CREATE SEQUENCE SM_USER_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

INSERT INTO SM_USER_TB(USER_NO, USER_ID, USER_PW, USER_EMAIL, USER_BIRTH, USER_GENDER) VALUES(SM_USER_SEQ.NEXTVAL, 'user1', 'test', 'user1@email.com', '20000101', 1);
INSERT INTO SM_USER_TB(USER_NO, USER_ID, USER_PW, USER_EMAIL, USER_BIRTH, USER_GENDER) VALUES(SM_USER_SEQ.NEXTVAL, 'user2', 'test', 'user2@email.com', '20000202', 2);

---------------------------------------------------------------------------------

CREATE TABLE SM_LOG_TB
(LOG_NO NUMBER(4) CONSTRAINT LOG_NO_TB_PK PRIMARY KEY,
LOG_USER_NO NUMBER(4) NOT NULL,
LOG_USER_IP VARCHAR2(20) NOT NULL,
LOG_TYPE NUMBER(1) DEFAULT 1,
LOG_CONTENT VARCHAR2(100),
LOG_CRE_DATE DATE DEFAULT SYSDATE,
CONSTRAINT LOG_USER_NO_FK FOREIGN KEY(LOG_USER_NO)
REFERENCES SM_USER_TB(USER_NO)
);

COMMENT ON TABLE SM_LOG_TB IS '로그';
COMMENT ON COLUMN SM_LOG_TB.LOG_NO IS '고유번호';
COMMENT ON COLUMN SM_LOG_TB.LOG_USER_NO IS '사용자TB 고유번호';
COMMENT ON COLUMN SM_LOG_TB.LOG_USER_IP IS '사용자 IP';
COMMENT ON COLUMN SM_LOG_TB.LOG_TYPE IS '이벤트 종류(1:로그인 2:검색 3:좋아요 4:추천 (사용자가 발생시킨 이벤트 종류))';
COMMENT ON COLUMN SM_LOG_TB.LOG_CONTENT IS '내용';
COMMENT ON COLUMN SM_LOG_TB.LOG_CRE_DATE IS '생성일';

CREATE SEQUENCE SM_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

INSERT INTO SM_LOG_TB(LOG_NO, LOG_USER_NO, LOG_USER_IP, LOG_TYPE) VALUES(SM_LOG_SEQ.NEXTVAL, 1, '192.168.0.69', 1);
INSERT INTO SM_LOG_TB(LOG_NO, LOG_USER_NO, LOG_USER_IP, LOG_TYPE) VALUES(SM_LOG_SEQ.NEXTVAL, 2, '192.168.0.68', 1);

---------------------------------------------------------------------------------

CREATE TABLE SM_WWH_TB
(WWH_NO NUMBER(4) CONSTRAINT WWH_NO_TB_PK PRIMARY KEY,
WWH_LOC NUMBER(1) NOT NULL,
WWH_TIME VARCHAR2(50),
WWH_DATE VARCHAR2(50),
WWH_FORECAST VARCHAR2(50),
WWH_TEMP NUMBER(2),
WWH_PREC NUMBER(3),
WWH_WIND NUMBER(4),
WWH_CRE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SM_WWH_TB IS '주간 날씨';
COMMENT ON COLUMN SM_WWH_TB.WWH_NO IS '고유번호';
COMMENT ON COLUMN SM_WWH_TB.WWH_LOC IS '지역 번호(1: 서울 2: 강릉 3: 태백 4: 대전 5: 광주 6:울산)';
COMMENT ON COLUMN SM_WWH_TB.WWH_TIME IS '시간';
COMMENT ON COLUMN SM_WWH_TB.WWH_DATE IS '날짜';
COMMENT ON COLUMN SM_WWH_TB.WWH_FORECAST IS '예보 날씨(그림)';
COMMENT ON COLUMN SM_WWH_TB.WWH_TEMP IS '온도';
COMMENT ON COLUMN SM_WWH_TB.WWH_PREC IS '강우량';
COMMENT ON COLUMN SM_WWH_TB.WWH_WIND IS '풍속';
COMMENT ON COLUMN SM_WWH_TB.WWH_CRE_DATE IS '생성일';

CREATE SEQUENCE SM_WWH_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

---------------------------------------------------------------------------------

CREATE TABLE SM_TNWH_TB
(TNWH_NO NUMBER(4) CONSTRAINT TNWH_NO_TB_PK PRIMARY KEY,
TNWH_LOC NUMBER(1) NOT NULL,
TNWH_TIME VARCHAR2(50),
TNWH_DATE VARCHAR2(50),
TNWH_FORECAST VARCHAR2(50),
TNWH_TEMP NUMBER(2),
TNWH_PREC NUMBER(3),
TNWH_WIND NUMBER(4),
TNWH_CRE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SM_TNWH_TB IS '오늘 내일 날씨';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_NO IS '고유번호';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_LOC IS '지역 번호(1: 서울 2: 강릉 3: 태백 4: 대전 5: 광주 6:울산)';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_TIME IS '시간';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_DATE IS '날짜';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_FORECAST IS '예보 날씨(그림)';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_TEMP IS '온도';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_PREC IS '강우량';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_WIND IS '풍속';
COMMENT ON COLUMN SM_TNWH_TB.TNWH_CRE_DATE IS '생성일';

CREATE SEQUENCE SM_TNWH_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

---------------------------------------------------------------------------------
DROP TABLE SM_RCD_TB;
CREATE TABLE SM_RCD_TB
(RCD_NO NUMBER(4) CONSTRAINT RCD_NO_TB_PK PRIMARY KEY,
RCD_TNWH_NO NUMBER(4),
RCD_TITLE VARCHAR2(200),
RCD_URL VARCHAR2(100),
RCD_TYPE NUMBER(1),
RCD_CRE_DATE DATE DEFAULT SYSDATE,
CONSTRAINT RCD_TNWH_NO_FK FOREIGN KEY(RCD_TNWH_NO)
REFERENCES SM_TNWH_TB(TNWH_NO)
);

COMMENT ON TABLE SM_RCD_TB IS '추천';

COMMENT ON COLUMN SM_RCD_TB.RCD_NO IS '고유번호';
COMMENT ON COLUMN SM_RCD_TB.RCD_TNWH_NO IS '오늘 내일 날씨TB 고유번호';
COMMENT ON COLUMN SM_RCD_TB.RCD_TITLE IS '제목';
COMMENT ON COLUMN SM_RCD_TB.RCD_URL IS 'URL';
COMMENT ON COLUMN SM_RCD_TB.RCD_TYPE IS '추천 종류(1: 노래 2: 활동 3: 음식)';
COMMENT ON COLUMN SM_RCD_TB.RCD_CRE_DATE IS '생성일';

CREATE SEQUENCE SM_RCD_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

---------------------------------------------------------------------------------

CREATE TABLE SM_SHD_TB
(SHD_NO NUMBER(4) CONSTRAINT SHD_NO_TB_PK PRIMARY KEY,
SHD_CONTENT VARCHAR2(200),
RCD_CRE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SM_SHD_TB IS '크롤링 스케쥴 관리';
COMMENT ON COLUMN SM_SHD_TB.SHD_NO IS '고유번호';
COMMENT ON COLUMN SM_SHD_TB.SHD_CONTENT IS '내용';
COMMENT ON COLUMN SM_SHD_TB.RCD_CRE_DATE IS '생성일';

CREATE SEQUENCE SM_SHD_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
