ACCEPT VEMPNO prompt '사번을 입력하세요 :  ' 

DECLARE 
	CURSOR C1(VEMPNO NUMBER) IS
		SELECT EMPNO,ENAME , JOB ,MGR
		FROM EMP
		WHERE EMPNO = VEMPNO;


BEGIN
	FOR C2 IN C1(&VEMPNO) LOOP

	DBMS_OUTPUT.PUT_LINE(C2.EMPNO||' '||C2.ENAME||' '||C2.JOB||' '||C2.MGR);
	END LOOP;

END;
/
